version: 2
sources:
  - name: demo
    database: DEMO
    schema: DEMO_SCHEMA
    tables:
      - name: bike
      - name: weather
      - name: amortan_mock_orders
      



  - name: US_CRIME
    database: US_CRIME
    schema: CYBERSYN
    tables:
      - name: URBAN_CRIME_INCIDENT_LOG
      



      
